# Generated by Django 5.1.4 on 2025-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_bandwidthusage_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OutboundTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_address', models.CharField(max_length=255)),
                ('remote_address', models.CharField(max_length=255)),
                ('remote_port', models.IntegerField()),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('packets_sent', models.BigIntegerField()),
                ('packets_received', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bandwidthusage',
            old_name='received',
            new_name='received_kb',
        ),
        migrations.RenameField(
            model_name='bandwidthusage',
            old_name='sent',
            new_name='sent_kb',
        ),
        migrations.RenameField(
            model_name='bandwidthusage',
            old_name='total',
            new_name='total_kb',
        ),
        migrations.RenameField(
            model_name='cpuusage',
            old_name='usage',
            new_name='cpu_usage',
        ),
        migrations.RenameField(
            model_name='openport',
            old_name='process',
            new_name='process_name',
        ),
        migrations.RemoveField(
            model_name='establishedconnection',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='openport',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='establishedconnection',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
