# Generated by Django 5.1.7 on 2025-05-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_cronjobmodification_logentry_outboundtraffic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BandwidthUsage',
        ),
        migrations.DeleteModel(
            name='CPUUsage',
        ),
        migrations.DeleteModel(
            name='CronJobModification',
        ),
        migrations.DeleteModel(
            name='EstablishedConnection',
        ),
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='OpenPort',
        ),
        migrations.DeleteModel(
            name='OutboundTraffic',
        ),
    ]
